# Generated by Django 2.1.1 on 2018-11-08 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quartet_trail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartetTrailDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='The class name of the model', max_length=255)),
                ('model_pk', models.CharField(db_index=True, help_text='The primary key of the model, could be an integer or anything else', max_length=255)),
                ('username', models.CharField(db_index=True, help_text='The username of the user who triggered this action', max_length=255)),
                ('date', models.DateTimeField(help_text='The date when the change occurred')),
                ('change', models.TextField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
        ),
    ]
