# Generated by Django 2.1.3 on 2018-12-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0002_historicalfilter_historicalrulefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrulefilter',
            name='break_on_true',
            field=models.BooleanField(default=False, help_text='If this Rule Filter finds its search value and there are more filters to search against, this will cause the filter logic to stop looking for matches if this rule filter search is successful.', verbose_name='Break on True'),
        ),
        migrations.AddField(
            model_name='historicalrulefilter',
            name='default',
            field=models.BooleanField(default=False, help_text='If this is set to true, then this rule filter will be selected if no rule filters prior to matched their search values.', verbose_name='Default'),
        ),
    ]
