# Generated by Django 2.1.5 on 2019-01-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0004_auto_20190107_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfilter',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Filter'},
        ),
        migrations.AddField(
            model_name='historicalrulefilter',
            name='description',
            field=models.CharField(help_text='A short description of what this rule filter does.', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='historicalrulefilter',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of the rule filter.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicallistbasedregion',
            name='number_replenishment_size',
            field=models.IntegerField(default=5000, help_text='The size that the outbound message will request from the third-party system, if numbers available are low. E.g.: 500', verbose_name='Number Replenishment Size'),
        ),
        migrations.AlterField(
            model_name='historicallistbasedregion',
            name='processing_class_path',
            field=models.CharField(default='list_based_flavorpack.processing_classes.third_party_processing.processing.ThirdPartyProcessingClass', help_text='The full python path to the class that will be processing region allocations', max_length=150, verbose_name='Processing Class Path'),
        ),
    ]
