# Generated by Django 2.1.5 on 2019-02-15 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0005_auto_20190128_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalauthenticationinfo',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Authentication Info'},
        ),
        migrations.AlterModelOptions(
            name='historicalendpoint',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical End Point'},
        ),
        migrations.AlterField(
            model_name='historicallistbasedregion',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
