# Generated by Django 2.2.2 on 2019-06-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0009_historicaltradeitem_pack_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalauthenticationinfo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcompanytype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalendpoint',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalepcisoutputcriteria',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfilter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallistbasedregion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallocationfield',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallocationidentifier',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallocationtype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmeasurement',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpool',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingparameters',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrandomizedregion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresponse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresponserule',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresponsetemplate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresponsetemplate_pool',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrule',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrulefilter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalruleparameter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsequentialregion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstep',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstepparameter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltaskparameter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltradeitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltradeitemfield',
            name='history_user',
        ),
        migrations.AddField(
            model_name='historicalauthenticationinfo',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalcompanytype',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalendpoint',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalepcisoutputcriteria',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalfilter',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicallistbasedregion',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicallocationfield',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicallocationidentifier',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicallocationtype',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalmeasurement',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalpool',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalprocessingparameters',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalrandomizedregion',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalresponse',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalresponserule',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalresponsetemplate',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalresponsetemplate_pool',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalrule',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalrulefilter',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalruleparameter',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalsequentialregion',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalstep',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalstepparameter',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicaltaskparameter',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicaltradeitem',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicaltradeitemfield',
            name='history_user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='username'),
        ),
    ]
