# Generated by Django 2.2.7 on 2019-12-19 16:03

from django.db import migrations, models
import list_based_flavorpack.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0012_historicaltradeitem_package_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistbasedregion',
            name='database_name',
            field=models.CharField(blank=True, default=list_based_flavorpack.models.haikunate, help_text='The name of the database file if this is a database range.', max_length=50, null=True, verbose_name='Database File'),
        ),
        migrations.AlterField(
            model_name='historicallistbasedregion',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid1, help_text='If this range utilizes list-based files, then this willbe the name of the file located in the directory path.', verbose_name='File Name'),
        ),
    ]
