# Generated by Django 3.0.1 on 2019-12-19 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0013_auto_20191219_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallistbasedregion',
            name='machine_name',
            field=models.CharField(db_index=True, help_text='A url/api-friendly unique key for use in API calls and such.', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-\\_]*$', 'Only numbers and letters are allowed. Invalid API Key.')], verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='historicalpool',
            name='machine_name',
            field=models.CharField(db_index=True, help_text='A url/api-friendly unique key for use in API calls and such.', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-\\_]*$', 'Only numbers and letters are allowed. Invalid API Key.')], verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='historicalrandomizedregion',
            name='machine_name',
            field=models.CharField(db_index=True, help_text='A url/api-friendly unique key for use in API calls and such.', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-\\_]*$', 'Only numbers and letters are allowed. Invalid API Key.')], verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='historicalsequentialregion',
            name='machine_name',
            field=models.CharField(db_index=True, help_text='A url/api-friendly unique key for use in API calls and such.', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-\\_]*$', 'Only numbers and letters are allowed. Invalid API Key.')], verbose_name='API Key'),
        ),
    ]
