# Generated by Django 3.0.2 on 2020-02-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0015_historicaloutboundmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaloutboundmapping',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Outbound Mapping'},
        ),
    ]
