# Generated by Django 3.0.2 on 2020-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0016_auto_20200221_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrulefilter',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rule Filter'},
        ),
        migrations.AlterField(
            model_name='historicallistbasedregion',
            name='processing_class_path',
            field=models.CharField(default='list_based_flavorpack.processing_classes.third_party_processing.processing.DBProcessingClass', help_text='The full python path to the class that will be processing region allocations', max_length=150, verbose_name='Processing Class Path'),
        ),
        migrations.AlterField(
            model_name='historicalrulefilter',
            name='break_on_true',
            field=models.BooleanField(default=True, help_text='If this Rule Filter finds its search value and there are more filters to search against, this will cause the filter logic to stop looking for matches if this rule filter search is successful.', verbose_name='Break on True'),
        ),
        migrations.AlterField(
            model_name='historicalrulefilter',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of what this rule filter does.', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalrulefilter',
            name='search_type',
            field=models.CharField(choices=[('regex', 'Regular Expression'), ('search', 'Text Search')], default='search', help_text='Regular Expression (regex) or Text Search (text). A regular expression that matches something in the inbound data or a plain text search value containing a string that can be matched within the inbound data.', max_length=10, verbose_name='Search Type'),
        ),
    ]
