# Generated by Django 3.1.4 on 2021-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_trail', '0019_auto_20200929_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalresponse',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Request and Response'},
        ),
        migrations.AddField(
            model_name='historicalresponse',
            name='response',
            field=models.TextField(blank=True, help_text='The response data', null=True, verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='historicalresponse',
            name='task_name',
            field=models.CharField(default='', help_text='If a response rule was configured for the pool and the request was fulfilled, a task name will be supplied.', max_length=100, verbose_name='Task Name'),
            preserve_default=False,
        ),
    ]
